---
title: "MixedRegression"
author: "Tim Schneegans"
date: "4 Januar 2021"
output: html_document
---

```{r setup, message=FALSE, warning=FALSE}
setwd("C:/Users/User/GitHub/WebET_Analysis")
# https://gist.github.com/stevenworthington/3178163
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}
ipak(c("knitr",
       "dplyr",
       'readr',
       "rsq",
       'lme4',
       "ICC",
       'ggplot2',
       'GGally',
       'reshape2',
       'lme4',
       'compiler',
       'parallel',
       'boot',
       'lattice',
       "lmerTest", # Erhalte p-Werte
       "tinytex")
    )

knitr::opts_chunk$set(echo = TRUE)
options(scipen=999) # Show R markdown output as Integers
```

# Prep data
```{r data}
data_et_fix <- read_csv('data_rInput/data_et_fix.csv')
data_trial_fix <- read_csv('data_rInput/data_trial_fix.csv')
data_subject <- read_csv('data_rInput/data_subject.csv')
names(data_trial_fix)
```

```{r}
data_trial_fix = data_trial_fix %>%
    filter(!is.na(precision))
nrow(data_trial_fix)
```

```{r}

```
## Visualize Predictors
```{r}
ggpairs(data_trial_fix[, c('x_pos', 'y_pos', 'precision', 'offset', 'fps')]) # Correlations
```


## Rescale
```{r}
```

# Null 
```{r}
data_trial_fix$x_pos_c = scale(data_trial_fix$x_pos)
data_trial_fix$y_pos_c = scale(data_trial_fix$y_pos)
data_trial_fix$withinTaskIndex_c = scale(data_trial_fix$withinTaskIndex)

m_null <- lmer(offset ~ x_pos_c + y_pos_c + withinTaskIndex_c + fps + (1 | run_id), 
               data = data_trial_fix)
# print(m_null, corr = FALSE)
summary(m_null)
```

# M1: Adding chin
```{r}
m1 <- lmer(offset ~ x_pos_c + y_pos_c + withinTaskIndex + chin + (1 | run_id), 
               data = data_trial_fix)
# print(m1, corr = FALSE)
summary(m1)
confint(m1, method="boot", n=50) # CI with Bootstrap does not need normality
```

# M2: 
```{r}
m2 <- lmer(offset ~ x_pos_c + y_pos_c + withinTaskIndex + chin + (1 | run_id), 
               data = data_trial_fix)
# print(m1, corr = FALSE)
summary(m2)
confint(m2, method="boot", n=50) # CI with Bootstrap does not need normality
```

```{r}
# average marginal predicted probability across a few different 
plotdat <- sapply(predictions[c(1, 20, 40, 60, 80, 100)], mean, na.rm=TRUE)

# get the means with lower and upper quartiles
# plotdat <- t(sapply(predictions, function(x) {
#               c(M = mean(x), quantile(x,
#                                       c(0.25, 0.75),
#                                       na.rm=na_rm))
#     }
#   )
# )

# add in LengthofStay values and convert to data frame
plotdat <- as.data.frame(cbind(plotdat, jvalues))

# better names and show the first few rows

colnames(plotdat) <- c("PredictedProbability", "optionIndex")
ggplot(plotdat, aes(x = optionIndex, y = PredictedProbability)) + geom_line() +
    ylim(c(0, 1))
```


# H5, H6
```{r prep data}
data_h56 <- read_csv('data_h56.csv')

data_h56$sight = factor(data_h56$sight, 
                    labels = c("glasses", "none", "contact", "perfect"))
data_h56$sight <- relevel(data_h56$sight, ref = "none")
```


## Null 
```{r nullModel}
null <- lmer(offset_perc ~ 1 + (1 | run_id), data_h56)
summary(null)
var.u0i <- unlist(VarCorr(null))
var.rti <- sigma(null)^2
var.u0i / (var.u0i + var.rti)
fixef(null)
ranef(null)
coef(null)
```

ICC = x%. x% of the variance relate to the variance between the subjects 
```{r ICC}
library(ICC)
data_h56$run_id_factor <- as.factor(data_h56$run_id)
ICCest(data_h56$run_id_factor, data_h56$offset_perc, alpha=.05, CI.type="THD")
fixef(null)
ranef(null)
coef(null)
```

## Random Intercept

### Offset
```{r}
model_ri_1 <- lmer(offset_perc ~ 1 + ethnic + positionIndex + fixation_nr + (1 | run_id), data_h56)
model_ri_2 <- lmer(offset_perc ~ 1 + ethnic + positionIndex + fixation_nr + chin + sight + glasses + (1 | run_id), data_h56)
summary(model_ri_2)
confint(model_ri_2, method="boot", n=1000) # CI with Bootstrap does not need normality 
```

### Precision
```{r}
model_ri_1 <- lmer(precision_perc ~ 1 + ethnic + positionIndex + fixation_nr + (1 | run_id), data_h56)
model_ri_2 <- lmer(precision_perc ~ 1 + ethnic + positionIndex + fixation_nr + chin + sight + glasses + (1 | run_id), data_h56)
summary(model_ri_2)
confint(model_ri_2, method="boot", n=1000) # CI with Bootstrap does not need normality 
```

## Random Slope
### Offset
```{r}
model_ri_1 <- lmer(offset_perc ~ 1 + ethnic + positionIndex + fixation_nr + (1 | run_id), data_h56)
model_ri_2 <- lmer(offset_perc ~ 1 + ethnic + positionIndex + fixation_nr + chin + sight + glasses + (1 + chin | run_id), data_h56)
summary(model_ri_2)
confint(model_ri_2, method="boot", n=1000) # CI with Bootstrap does not need normality 
```

### Precision
```{r}
model_ri_1 <- lmer(precision_perc ~ 1 + ethnic + positionIndex + fixation_nr + (1 | run_id), data_h56)
model_ri_2 <- lmer(precision_perc ~ 1 + ethnic + positionIndex + fixation_nr + chin + sight + glasses + (1 + chin | run_id), data_h56)
summary(model_ri_2)
confint(model_ri_2, method="boot", n=1000) # CI with Bootstrap does not need normality 
anova(model_ri_1, model_ri_2, refit=FALSE)
```