---
title: "Power Analysis"
author: 'Tim Schneegans'
date: '15.10.2020'
output:
  html_document:
    df_print: paged
  pdf_document: default
---

# Setup
## Packages & Time estimation
```{r setup, message=FALSE, warning=FALSE}
setwd("C:/Users/User/Google Drive/Masterarbeit/Analysis/APrioriPower")
# Package-Function: https://gist.github.com/stevenworthington/3178163
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}
ipak(c("knitr",
       "simr",
       "dplyr",
       "rsq",
       "tictoc",
       "tinytex"))
tic("total")

simrOptions("progress"=FALSE) # Do not show progress bar
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999) # Show R markdown output as Integers
simrOptions(progress=TRUE) #simr setting
```

## Simulation parameters 
```{r}
myNSim = 500
myBreaks = 25
```

## Dataset-Function
This dataset returns a dataset from a 3x3x3 Between-Subject-Design. Every subject does a certain number of trials. The variables "fps", "light", and "ethnicity" (3 levels) are randomly distributed. The treatment factors are balanced across the dataset.  
```{r}
kTrial = 3
nsubj = 20 

ds <- data.frame(
  # For each subject
  subj   = rep(factor(1:nsubj), each=2*kTrial),
  light  = rep(floor(runif(nsubj, 0, 1)+0.5), each=2*kTrial),
  ethnic = rep(floor(runif(nsubj, 0, 2.99)), each=2*kTrial),
  glasses = rep(rep(c(0, 1), each=2*kTrial), each=nsubj/2),
  visualAid = rep(rep(c(1:4), each=2*kTrial), nsubj/4),
  
  # For each trial
  trial  = rep(1:kTrial, 2*nsubj),
  fps    = 10+rnorm(2*nsubj*kTrial, mean=4, sd=6.68),
  offset = round(rnorm((2*nsubj*kTrial), mean=0.15, sd=0.15),
                 digits=2),
  chin   = rep(c(0, 1), each=kTrial, nsubj)
)

ds$visualAid <- factor(ds$visualAid, levels = c(1, 2, 3, 4), 
                    labels = c("noCorrect", "short", "long", "progressive"))
ds$visualAid <- relevel(ds$visualAid, ref = "noCorrect")
ds$ethnic <- factor(ds$ethnic, levels = c(0, 1, 2), 
                    labels = c("Cauc", "Black", "Asian"))
ds$ethnic <- relevel(ds$ethnic, ref = "Cauc")
ds$fps_c <- scale(ds$fps)
ds$light_c <- scale(ds$light)
```

# Random Slope
## Model
```{r}
defineRS <- function(mychin) {
  # Intercept and slopes for intervention, time1, time2,     intervention:time1, intervention:time2
  # Effects based on Semmelmann & Weigelt, 2018 - We take the other effects * 3 
  fixed <- c(0.15,   # Intercept
             0.001,  # Trial
             mychin,   # chin
             0.02, # glasses 
             0.005, # short
             0.005, # long
             0.001, # progressive
             0.0007, # Black
             0.007   # Asian
             )
  # Random intercepts for participants clustered by class, Variance from above
  # https://rstudio-pubs-static.s3.amazonaws.com/484106_6b51212f20164fdd88cd7cce89bdef79.html
  rand <- matrix(c(0.05^2, -0.0005, -0.0005, 0.03^2), 2, 2)
  # Extract residual sd
  res <- (1.218e-12^0.5)
  m <- makeLmer(offset ~ trial + chin + glasses + visualAid + ethnic  + (1 + chin |subj),
                fixef=fixed, VarCorr=rand, sigma=res, data=ds)
  return(m)
}
```

## Power
```{r, results="hide", message=FALSE, warning=FALSE}
treat = c(0.02)
output = list(rep(0, length(treat)))
for(i in 1:length(treat)) {
  m <- defineRS(mychin=treat[i])
  m <- extend(m, along="subj", n=500)
  pc <- powerCurve(m, along="subj", 
             test = fixed("glasses", method="t"), 
             breaks=seq(200, 300, myBreaks), 
             nsim=myNSim)
  output[[i]] <- list(m, pc)
  names(output[[i]]) <- c("Model", "Power Curve")
}
```

## Output
```{r}
output
```

# Running time 
```{r}
toc()
```