function [largest_clusters] = fit_clusters(...
    data, n_clusters, aoi_width, aoi_height, tolerance, ...
    plot_results)   
    
    if plot_results
        run_name = int2str(unique(data(:, 1)));
        mkdir(fullfile('plots', run_name));
        scatter_plot(data(:, 3), data(:, 4), ...
            fullfile('plots', run_name, 'uncorrected.png'));
    end
    grandmean=mean(data(:, (3:4))); %Find center of all eye data points

    % Assing clusters
    clusters = clusterdata(...
        data(:, 3:4), ...
        'linkage','centroid', ...
        'savememory','on', ...
        'maxclust', n_clusters);
    
    % col: 8
    data=[data clusters];   

    if plot_results
        scatter_plot_clusters(data(:, 3), data(:, 4), data(:, 6), ...
            grandmean, ...
            fullfile('plots', run_name, 'clusters.png'));
    end

    % col 1: cluster number
    % col 2: number of data points in each cluster (accumarray),
    % col 3: mean cluster x position
    % col 4: mean cluster y position
    % col 5: left border
    % col 6: right border
    % col 7: top border
    % col 8: bottom borter
    cluster_aoi_info = get_cluster_aoi_info(...
        data, clusters, n_clusters, aoi_width, aoi_height);

    % col 1-8: see cluster_aoi_info
    % col 9: corner (TL, TR, BL, BR)
    largest_clusters = find_largest_clusters(...
        cluster_aoi_info, grandmean, tolerance);
    
    % Plot resulting clusters
    if plot_results
        data_largest_clusters = data(...
            (...
                ismember(data(:, 6), largest_clusters(:, 1)) & ...
                (data(:, 6) > 0)...
            ), :);
        scatter_plot_clusters(...
            data_largest_clusters(:, 3), ...
            data_largest_clusters(:, 4), ...
            data_largest_clusters(:, 6), ...
            grandmean, ...
            fullfile('plots', run_name, 'corner_clusters.png'));
    end
end