source(file.path(root, 'utils', 'r', 'geom_split_violin.R'))
source(file.path(root, 'utils', 'r', 'merge_by_subject.R'))
source(file.path(root, 'utils', 'r', 'summarize_datasets.R'))
source(file.path(root, 'utils', 'r', 'get_packages.R'))
source(file.path(root, 'utils', 'r', 'remove_runs.R'))
source(file.path(root, 'utils', 'r', 'add_log_k.R'))
source(file.path(root, 'utils', 'r', 'remove_na_et_indices.R'))
source(file.path(root, 'utils', 'r', 'add_x_count.R'))
source(file.path(root, 'utils', 'r', 'plot_outcome_variance.R'))
source(file.path(path_analysis, 'anova_fix_data.R'))
source(file.path(path_analysis, 'scatter_matrix_trial.R'))
source(file.path(path_analysis, 'scatter_matrix_subject.R'))
source(file.path(path_analysis, 'compare.R'))
source(file.path(path_analysis, 'effects.R'))
source(file.path(path_analysis, 'robust.R'))
source(file.path(path_analysis, 'assumptions.R'))
source(file.path(path_analysis, 'transformation.R'))
source(file.path(path_analysis, 'icc.R'))
source(file.path(path_analysis, 'prep_data.R'))


library(brms)
library(boot)
library(boxcoxmix)
library(broom)
library(car)
library(compiler)
library(data.table)
library(DHARMa)
library(GGally)
library(HLMdiag)
library(Hmisc)
library(influence.ME)
library(ICC)
library(knitr)
library(lme4)
library(lattice)
library(lme4)
library(lmerTest) # Erhalte p-Werte
library(nlme)
library(parallel)
library(reshape)
library(reshape2)
library(RcppParallel)
library(rsq)
library(tidyverse)
library(tinytex)