function pchoice = GetPChoice(k,aSS,aLL,tLL,choseLL)
      % By Chabris/Laibson 2008 (Likelihood function defined)
      % We calculate the likelihood of the data (real choice) which either
      % takes value 0 or value 1 (immediate or tLLed reward respectively)
      % via the logit functions on the right hand sight... 
    pchoice = choseLL .* ...
        (...
            exp(aLL ./ (1 + k*tLL)) ./ ...
            (exp(aSS) + exp(aLL ./ (1 + k*tLL)))...
        ) + ...
        (1-choseLL) .* ...
        (...
            1 - (...
                    exp(aLL ./ (1 + k*tLL)) ./ ...
                    (exp(aSS) + exp(aLL ./ (1 + k*tLL)))...
                )...
        );
end